### ISSUE TITLE
leading-0の扱いについて

### ISSUE THREAD

**Issue by nabefuta220** [TUT-class-sato/SDM-report2#131]
先頭が0であり、全ての文字列が数字で構成されている文字列は先頭の0を取り除いた10進数の整数として取り扱うべきですか？
例えば“012”という文字列は12として取り扱うべきですか？

余談ですが、python3ではint(“012”)は整数の12として認識されました。

**Comment by YukinoriSato** [comment]
問題から読み取れる仕様では明確ではない部分になると思いますが、この質問(issue)で取り上げている曖昧さは、どう解釈するかも含めて開発者側が良い解釈を考えてその方針に沿ってコーディングすればよいと思います。以下は、私の考えになりますが、“012”のように既に文字列としてテストケースに入れているのであれば、文字列で、数字の12と解釈するのは飛躍しているような気もします。012としてダブルクオテーションなしで入力するのは、整数にするべきか、0が先頭から始まる整数はないとするかは、後者のほうが多くの人が正しいと思う気もします。

また、a=012と代入するとPython3ではエラーになるようです。

**Comment by nabefuta220** [comment]
こちらの環境(Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux)でも確認したところ、`a=012`(クォーテーションなし)はSyntaxErrorが起きました。そのため、calcの引数として012のような(文字列ではない)整数はメソッドに入る前に例外が投げれると考えられます。

私の考えとしては、leading-0を許容してほしいならば、　<https://atcoder.jp/contests/past201912-open/tasks/past201912_a>の
>S が 3 桁の整数である場合 (0 で始まる場合を含む) はその 2 倍の値を出力し、そうでなければ error と出力するプログラムを作成せよ。

のように、仕様として明記されるはずだとして考え、先頭が0で後に数字が続く文字列が引数として与えられた場合は-1を返すべきだと考えます。

**Comment by nabefuta220** [comment]
また、採点について提案があるのですが、もし、"012"などの先頭が0で後に数字が続く文字列が整数として扱うべきが曖昧ならば、`そのような値が入力として与えられたときの動作は未定義である`として、テストにはそのような入力は含めず、(テストケースを作成する課題においても、そのような入力を考慮する必要はない)もし、そのような値が入力として与えられた場合は出力は任意の値で構わないようにするのはいかがでしょうか?

**Comment by YukinoriSato** [comment]
レポートとしましては、"012"など先頭が0で後に数字が続く場合の取り扱いは、出題した仕様においては未定義でお願いします。なので、開発者側の裁量の設計として、自身で定義したテストケースを作ってその動作を確認してもよいですし、テストケースに取り上げなくても問題ありません。
