### ISSUE TITLE
calc関数の引数・戻り値の型について

### ISSUE THREAD

**Issue by nabefuta220** [TUT-class-sato/SDM-report2#138]
calc関数の引数・戻り値について質問です。

calcの引数の型について、

calc_mul.pyでcalc関数が使われている箇所を確認したところ、input関数の戻り値は`str`であるため、この点から見ると引数の型は`str`であることが**保証されている**と見ても良さそうな一方、test_case.pyではcalc関数の引数として`int`,`str`,`float`があるため、calcの引数の型は`Any`(任意の型を受け入れる)とみなしてよろしいでしょうか?

また、calc関数の戻り値の型について、

最初の状態では`float`(引数が有効な値であった場合)、`int`(引数が無効な値であった場合)になっているのに対し、test_calc.pyではcalc関数と比較している値がすべて`int`であるため、calcの戻り値の型はどのような場合であっても`int`である必要があるとみてよろしいでしょうか?

(本当は浮動小数点特有の誤差を使って撃墜したかったのですが、有効なケースで全探索をしても撃墜できなかったため質問させていただきます)

**Comment by YukinoriSato** [comment]
便宜上、引数について関数の冒頭でstrにキャストしておりますが、calcの引数の型は任意の型を受け入れます。戻り値は特に指定はないのですが、レポート課題の仕様としての出力の集合がintの範囲内なので、intで特に問題ないと思いますが、必ずしもintでなくてもよいと思います。

**Comment by YukinoriSato** [comment]
issue closed
